=== AndreaAcero/MotoGP-Desktop/xml/circuito.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://www.uniovi.es" elementFormDefault="qualified" targetNamespace="http://www.uniovi.es" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	
<xs:element name="circuito">
	<xs:complexType>
		<xs:sequence>
			<!--Nombre del circuito-->
			<xs:element name="nombre" type="xs:string"/>

			<!--Longitud total del circuito-->
			<xs:element name="longitud">
			<xs:complexType>
				<xs:simpleContent>
				<xs:extension base="xs:decimal">
					<xs:attribute name="unidades" type="xs:string" use="required"/>
				</xs:extension>
				</xs:simpleContent>
			</xs:complexType>
			</xs:element>

			<!--Anchura de la pista-->
			<xs:element name="anchura">
			<xs:complexType>
				<xs:simpleContent>
				<xs:extension base="xs:decimal">
					<xs:attribute name="unidades" type="xs:string" use="required"/>
				</xs:extension>
				</xs:simpleContent>
			</xs:complexType>
			</xs:element>
			
			<!--Fecha de la carrera-->
			<xs:element name="fecha" type="xs:date"/>
			
			<!--Hora de inicio de la carrera-->
			<xs:element name="hora" type="xs:time"/>
			
			<!--Número de vueltas de la carrera-->	
			<xs:element name="numVueltas">
				<xs:simpleType>
					<xs:restriction base="xs:positiveInteger">
						<xs:minInclusive value="1"/>
						<xs:maxInclusive value="500"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>

			<!--Localidad donde se encuentra el circuito-->
			<xs:element name="localidad" type="xs:string"/>

			<!--País donde se encuentra el circuito-->
			<xs:element name="pais" type="xs:string"/>

			<!--Patrocinador principal del circuito-->
			<xs:element name="patrocinador" type="xs:string"/>

			<!--Referencias del circuito-->
			<xs:element name="referencias">	
				<xs:complexType>
					<xs:sequence>
						<xs:element name="referencia" type="xs:anyURI" minOccurs="3" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>

			<!--Galería de fotos del circuito-->
			<xs:element name="galeriaFotos">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="foto" type="xs:string" minOccurs="1" maxOccurs="5"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>

			<!--Galería de vídeos del circuito-->
			<xs:element name="galeriaVideos">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="video" type="xs:string" minOccurs="1" maxOccurs="3"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>

			<!--Punto de origen del circuito-->
			<xs:element name="puntoOrigen">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="longitud">
							<xs:simpleType>
								<xs:restriction base="xs:decimal">
									<xs:minInclusive value="-180.0"/>
									<xs:maxInclusive value="180.0"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:element>	
						<xs:element name="latitud">
							<xs:simpleType>
								<xs:restriction base="xs:decimal">
									<xs:minInclusive value="-90.0"/>
									<xs:maxInclusive value="90.0"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:element>
						<xs:element name="altitud">
							<xs:simpleType>
								<xs:restriction base="xs:decimal">
									<xs:minInclusive value="-500.0"/>
									<xs:maxInclusive value="9000.0"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:element>					
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<!--Tramos del circuito-->
			<xs:element name="tramos">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="tramo" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>

                    <!-- distancia pasa a ser elemento para que cuelgue del tramo -->
                    <xs:element name="distancia">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:decimal">
                            <xs:attribute name="unidades" type="xs:string" use="required"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>

                    <xs:element name="longitud">
						<xs:complexType>
							<xs:simpleContent>
							<xs:extension base="xs:decimal">
								<xs:attribute name="unidades" type="xs:string" use="required"/>
							</xs:extension>
							</xs:simpleContent>
						</xs:complexType>
					</xs:element>

                    <xs:element name="latitud">
						<xs:complexType>
							<xs:simpleContent>
							<xs:extension base="xs:decimal">
								<xs:attribute name="unidades" type="xs:string" use="required"/>
							</xs:extension>
							</xs:simpleContent>
						</xs:complexType>
					</xs:element>

                    <xs:element name="altitud">
						<xs:complexType>
							<xs:simpleContent>
							<xs:extension base="xs:decimal">
								<xs:attribute name="unidades" type="xs:string" use="required"/>
							</xs:extension>
							</xs:simpleContent>
						</xs:complexType>
					</xs:element>

                  </xs:sequence>

                  <!-- sector sigue como atributo del tramo -->
                  <xs:attribute name="sector" type="xs:positiveInteger" use="required"/>

                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
			
			<!--Vencedor de la carrera-->
			<xs:element name="vencedor">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="nombre" type="xs:string"/>
						<xs:element name="tiempo" type="xs:duration"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>

			<!--Clasificación Mundial-->
			<!-- Clasificación del mundial -->
			<xs:element name="clasificacionMundial">
			<xs:complexType>
				<xs:sequence>
				<xs:element name="piloto" minOccurs="3" maxOccurs="3">
					<xs:complexType>
					<xs:sequence>
						<xs:element name="nombre" type="xs:string"/>
						<xs:element name="puntos">
						<xs:simpleType>
							<xs:restriction base="xs:integer">
							<xs:minInclusive value="0"/>
							<xs:maxInclusive value="500"/>
							</xs:restriction>
						</xs:simpleType>
						</xs:element>
					</xs:sequence>
					<xs:attribute name="posicion">
						<xs:simpleType>
						<xs:restriction base="xs:positiveInteger">
							<xs:minInclusive value="1"/>
							<xs:maxInclusive value="3"/>
						</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
					</xs:complexType>
				</xs:element>
				</xs:sequence>
			</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:element>
</xs:schema>

=== AndreaAcero/MotoGP-Desktop/xml/circuitoEsquema.xml
<?xml version="1.0" encoding="UTF-8"?>
<circuito xmlns="http://www.uniovi.es"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://www.uniovi.es circuito.xsd">

          <nombre>"Silverstone Circuit"</nombre>
   
    <longitud unidades="metros">5.901</longitud>
    <anchura unidades="metros">15</anchura>


    <fecha>2025-05-25</fecha>
    <hora>14:00:00</hora>
    <numVueltas>20</numVueltas>
    <localidad>Silverstone</localidad>
    <pais>Reino Unido</pais>
    <patrocinador>Tissot</patrocinador>

    <referencias>
        <referencia>https://www.silverstone.co.uk/events/british-grand-prix-motogp</referencia>
        <referencia>https://www.motogp.com/es/calendar/2025/event/great-britain/98f03e76-5837-4b99-a5a5-57c367c8ba1b?tab=overview</referencia>
        <referencia>https://www.motogp.com/es/gp-results/2025/gbr/motogp/rac/classification</referencia>
    </referencias>


    <galeriaFotos>
        <foto>../multimedia/PanoramicaSilverstone.jpg</foto>
        <foto>../multimedia/rectaMetaSilverstone.jpg</foto>
        <foto>../multimedia/ImgCircuitoSilvertone.jpg</foto>
    </galeriaFotos>

    <galeriaVideos>
        <video>../multimedia/CircuitoSilverstone.mp4</video>
        <video>../multimedia/ResumenCarreraSilverstone.mp4</video>
    </galeriaVideos>

    <puntoOrigen>
        <longitud>-1.023496004592915</longitud>
        <latitud>52.0682791305414</latitud>
        <altitud>144.6525967819629</altitud>
    </puntoOrigen>

<tramos> 
  <tramo sector="1">
    <distancia unidades="m">410.06</distancia>
    <longitud unidades="°">-1.019830128447543</longitud>
    <latitud unidades="°">52.07119829430768</latitud>
    <altitud unidades="m">150.1671797303125</altitud>
  </tramo>
  <tramo sector="1">
    <distancia unidades="m">74.27</distancia>
    <longitud unidades="°">-1.01876972201569</longitud>
    <latitud unidades="°">52.07134415664211</latitud>
    <altitud unidades="m">149.9952590991023</altitud>
  </tramo>
  <tramo sector="1">
    <distancia unidades="m">103.59</distancia>
    <longitud unidades="°">-1.017269282525106</longitud>
    <latitud unidades="°">52.07121244518698</latitud>
    <altitud unidades="m">151.9052034266277</altitud>
  </tramo>
  <tramo sector="1">
    <distancia unidades="m">49.71</distancia>
    <longitud unidades="°">-1.016542463552719</longitud>
    <latitud unidades="°">52.07122825932527</latitud>
    <altitud unidades="m">152.0305905851272</altitud>
  </tramo>
  <tramo sector="1">
    <distancia unidades="m">49.80</distancia>
    <longitud unidades="°">-1.015870069147684</longitud>
    <latitud unidades="°">52.07140083848225</latitud>
    <altitud unidades="m">152.4751135878318</altitud>
  </tramo>
  <tramo sector="1">
    <distancia unidades="m">188.62</distancia>
    <longitud unidades="°">-1.013718317150093</longitud>
    <latitud unidades="°">52.07246296568587</latitud>
    <altitud unidades="m">154.0310944885692</altitud>
  </tramo>
  <tramo sector="1">
    <distancia unidades="m">30.54</distancia>
    <longitud unidades="°">-1.013287107079902</longitud>
    <latitud unidades="°">52.0725350507166</latitud>
    <altitud unidades="m">153.8102213217404</altitud>
  </tramo>
  <tramo sector="1">
    <distancia unidades="m">19.62</distancia>
    <longitud unidades="°">-1.013071317516454</longitud>
    <latitud unidades="°">52.07241873087544</latitud>
    <altitud unidades="m">154.1562515771411</altitud>
  </tramo>
  <tramo sector="1">
    <distancia unidades="m">101.57</distancia>
    <longitud unidades="°">-1.012623624626834</longitud>
    <latitud unidades="°">52.07154769099485</latitud>
    <altitud unidades="m">155.0580407989825</altitud>
  </tramo>
  <tramo sector="1">
    <distancia unidades="m">24.01</distancia>
    <longitud unidades="°">-1.012347674521078</longitud>
    <latitud unidades="°">52.07141402193572</latitud>
    <altitud unidades="m">155.2689216279713</altitud>
  </tramo>
  <tramo sector="1">
    <distancia unidades="m">29.14</distancia>
    <longitud unidades="°">-1.011958212109717</longitud>
    <latitud unidades="°">52.0715205340105</latitud>
    <altitud unidades="m">155.5631005705005</altitud>
  </tramo>
  <tramo sector="1">
    <distancia unidades="m">90.88</distancia>
    <longitud unidades="°">-1.011549753559144</longitud>
    <latitud unidades="°">52.07229832321701</latitud>
    <altitud unidades="m">155.7046091314662</altitud>
  </tramo>
  <tramo sector="1">
    <distancia unidades="m">75.38</distancia>
    <longitud unidades="°">-1.011447246281119</longitud>
    <latitud unidades="°">52.07297332250932</latitud>
    <altitud unidades="m">154.732692690435</altitud>
  </tramo>
  <tramo sector="1">
    <distancia unidades="m">14.32</distancia>
    <longitud unidades="°">-1.01151071943674</longitud>
    <latitud unidades="°">52.07309605066666</latitud>
    <altitud unidades="m">154.7200446458884</altitud>
  </tramo>
  <tramo sector="1">
    <distancia unidades="m">18.21</distancia>
    <longitud unidades="°">-1.011684501782754</longitud>
    <latitud unidades="°">52.07322013638694</latitud>
    <altitud unidades="m">154.5194737588663</altitud>
  </tramo>
  <tramo sector="2">
    <distancia unidades="m">629.23</distancia>
    <longitud unidades="°">-1.018526758811774</longitud>
    <latitud unidades="°">52.07700642564061</latitud>
    <altitud unidades="m">152.4449821272436</altitud>
  </tramo>
  <tramo sector="2">
    <distancia unidades="m">60.46</distancia>
    <longitud unidades="°">-1.01938555505885</longitud>
    <latitud unidades="°">52.07713712517122</latitud>
    <altitud unidades="m">151.4207045637658</altitud>
  </tramo>
  <tramo sector="2">
    <distancia unidades="m">52.39</distancia>
    <longitud unidades="°">-1.020024408222121</longitud>
    <latitud unidades="°">52.07687674321814</latitud>
    <altitud unidades="m">151.3353831040847</altitud>
  </tramo>
  <tramo sector="2">
    <distancia unidades="m">82.92</distancia>
    <longitud unidades="°">-1.020197187696139</longitud>
    <latitud unidades="°">52.0761386587228</latitud>
    <altitud unidades="m">152.4751667361721</altitud>
  </tramo>
  <tramo sector="2">
    <distancia unidades="m">51.48</distancia>
    <longitud unidades="°">-1.020740138713085</longitud>
    <latitud unidades="°">52.07581775964901</latitud>
    <altitud unidades="m">152.5069987993567</altitud>
  </tramo>
  <tramo sector="2">
    <distancia unidades="m">61.57</distancia>
    <longitud unidades="°">-1.021570572343397</longitud>
    <latitud unidades="°">52.07603255451268</latitud>
    <altitud unidades="m">152.4013493429758</altitud>
  </tramo>
  <tramo sector="2">
    <distancia unidades="m">57.46</distancia>
    <longitud unidades="°">-1.021586968555575</longitud>
    <latitud unidades="°">52.07654917724236</latitud>
    <altitud unidades="m">152.1458959009825</altitud>
  </tramo>
  <tramo sector="2">
    <distancia unidades="m">168.77</distancia>
    <longitud unidades="°">-1.020384695049413</longitud>
    <latitud unidades="°">52.07787494022628</latitud>
    <altitud unidades="m">150.537850685179</altitud>
  </tramo>
  <tramo sector="2">
    <distancia unidades="m">65.58</distancia>
    <longitud unidades="°">-1.019688622588463</longitud>
    <latitud unidades="°">52.07828098103752</latitud>
    <altitud unidades="m">151.1402998022992</altitud>
  </tramo>
  <tramo sector="2">
    <distancia unidades="m">74.99</distancia>
    <longitud unidades="°">-1.018703917082977</longitud>
    <latitud unidades="°">52.07857856772953</latitud>
    <altitud unidades="m">151.1489598964246</altitud>
  </tramo>
  <tramo sector="2">
    <distancia unidades="m">55.44</distancia>
    <longitud unidades="°">-1.017902554314394</longitud>
    <latitud unidades="°">52.07865638678362</latitud>
    <altitud unidades="m">151.2426733177737</altitud>
  </tramo>
  <tramo sector="2">
    <distancia unidades="m">386.94</distancia>
    <longitud unidades="°">-1.012261269300879</longitud>
    <latitud unidades="°">52.07895531909693</latitud>
    <altitud unidades="m">153.7977281076318</altitud>
  </tramo>
  <tramo sector="2">
    <distancia unidades="m">48.32</distancia>
    <longitud unidades="°">-1.011623852600038</longitud>
    <latitud unidades="°">52.07876721887159</latitud>
    <altitud unidades="m">153.644091023256</altitud>
  </tramo>
  <tramo sector="2">
    <distancia unidades="m">52.31</distancia>
    <longitud unidades="°">-1.011136201090794</longitud>
    <latitud unidades="°">52.07840466015906</latitud>
    <altitud unidades="m">153.7827890881021</altitud>
  </tramo>

  <tramo sector="2">
    <distancia unidades="m">477.05</distancia>
    <longitud unidades="°">-1.010185091176228</longitud>
    <latitud unidades="°">52.07433866550169</latitud>
    <altitud unidades="m">154.6128979185694</altitud>
  </tramo>
  <tramo sector="2">
    <distancia unidades="m">48.49</distancia>
    <longitud unidades="°">-1.009923917116049</longitud>
    <latitud unidades="°">52.07393319498046</latitud>
    <altitud unidades="m">153.7976423841828</altitud>
  </tramo>
  <tramo sector="2">
    <distancia unidades="m">53.70</distancia>
    <longitud unidades="°">-1.009541204641218</longitud>
    <latitud unidades="°">52.07351137375181</latitud>
    <altitud unidades="m">153.2879930066213</altitud>
  </tramo>
  <tramo sector="2">
    <distancia unidades="m">49.17</distancia>
    <longitud unidades="°">-1.009664195999805</longitud>
    <latitud unidades="°">52.07307569210331</latitud>
    <altitud unidades="m">154.3747007736468</altitud>
  </tramo>
  <tramo sector="2">
    <distancia unidades="m">73.76</distancia>
    <longitud unidades="°">-1.010044679674073</longitud>
    <latitud unidades="°">52.07245498112735</latitud>
    <altitud unidades="m">155.6729751713994</altitud>
  </tramo>
  <tramo sector="2">
    <distancia unidades="m">39.26</distancia>
    <longitud unidades="°">-1.010123271757664</longitud>
    <latitud unidades="°">52.07210526191563</latitud>
